name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x Server/main07/gradlew
      - name: Build with Gradle
        working-directory: Server/main07
        run: ./gradlew clean build
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t timecapsule-cicd -f Server/main07/Dockerfile . 
          docker tag timecapsule-cicd dakyung/timecapsule-cicd:${GITHUB_SHA::7}
          docker push dakyung/timecapsule-cicd:${GITHUB_SHA::7}